const subjects = [
  // General Studies / Aptitude
  "General Knowledge",
  "Current Affairs",
  "Quantitative Aptitude",
  "Logical Reasoning",
  "Data Interpretation",
  "Verbal Ability",
  "Non-Verbal Reasoning",
  "General Awareness",
  "General Science",
  "Static GK",
  "Computer Awareness",
  "Mental Ability",
  "Decision Making",
  "Numerical Ability",
  "Analytical Reasoning",
  "Problem Solving",
  "Coding-Decoding",
  "Syllogism",
  "Seating Arrangement",
  "Blood Relations",
  "Direction Sense",
  "Input Output",

  // English Language
  "English Grammar",
  "Reading Comprehension",
  "Vocabulary",
  "Synonyms & Antonyms",
  "Sentence Correction",
  "Para Jumbles",
  "Fill in the Blanks",
  "Cloze Test",
  "Error Spotting",
  "Idioms and Phrases",

  // Hindi Language
  "Hindi Grammar",
  "संधि और समास",
  "हिंदी साहित्य",
  "मुहावरे और लोकोक्तियाँ",
  "गद्यांश अवबोधन",
  "वाक्य संशोधन",

  // UPSC & State PSCs
  "Indian Polity",
  "Indian Economy",
  "History of India",
  "Geography of India",
  "World Geography",
  "Environment and Ecology",
  "Indian Constitution",
  "Governance",
  "Ethics and Integrity",
  "Social Issues",
  "Science and Technology",
  "International Relations",
  "Art and Culture",
  "Disaster Management",
  "Security Issues",

  // Engineering Exams (NEET, GATE, etc.)
  "Mathematics",
  "Physics",
  "Chemistry",
  "Engineering Mathematics",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Computer Science",
  "Electronics and Communication",
  "Instrumentation Engineering",

  // Medical Exams (NEET, AIIMS, etc.)
  "Biology",
  "Botany",
  "Zoology",
  "Human Physiology",
  "Plant Physiology",
  "Genetics",
  "Biotechnology",
  "Ecology and Environment",
  "Anatomy",
  "Microbiology",
  "Biochemistry",

  // Commerce / MBA / Management Exams
  "Accountancy",
  "Business Studies",
  "Economics",
  "Marketing",
  "Finance",
  "Business Aptitude",
  "Management Principles",
  "Human Resource Management",
  "Quantitative Techniques",
  "Operations Research",
  "Cost Accounting",
  "Auditing",

  // Law Exams (CLAT, AILET, etc.)
  "Legal Aptitude",
  "Legal Reasoning",
  "Constitutional Law",
  "Indian Penal Code",
  "Contract Law",
  "Legal GK",
  "Torts Law",
  "Current Legal Affairs",

  // Teaching Exams (CTET, TETs, etc.)
  "Child Development and Pedagogy",
  "Educational Psychology",
  "Teaching Methodology",
  "Environmental Studies",
  "Mathematics Pedagogy",
  "Science Pedagogy",
  "Social Studies Pedagogy",
  "Language Pedagogy",

  // Miscellaneous / Specialized
  "Agriculture",
  "Animal Husbandry",
  "Forestry",
  "Veterinary Science",
  "Food Technology",
  "Bioinformatics",
  "Anthropology",
  "Sociology",
  "Psychology",
  "Public Administration",
  "Philosophy",
  "Statistics",
  "Geology",
  "History of Modern India",
  "Freedom Struggle",
  "Indian Art & Culture",
  "Urban Planning",
  "Rural Development",
  "Banking Awareness",
  "Insurance Awareness",
  "Financial Markets",
  "Taxation",
  "Corporate Law",
  "Maritime Law",

  // Languages (Optional for UPSC or other exams)
  "Sanskrit",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Gujarati",
  "Marathi",
  "Punjabi",
  "Bengali",
  "Odia",
  "Urdu",
  "Assamese",
  "Konkani",
  "Manipuri",
  "Bodo",
  "Kashmiri",
  "Nepali",
  "Dogri",
  "Maithili",
  "Santhali",
];
const getAllSubjects = () => {
  return subjects;
};
module.exports = { getAllSubjects };
